import Vue from 'vue'
import '@mdi/font/css/materialdesignicons.css'
import Vuetify,
{
    VBtn,
    VIcon,
    VAvatar,
    VAppBar,
    VAppBarNavIcon,
    VToolbarTitle,
    VSnackbar,
    VDialog,
    VCard,
    VCardText,
    VSpacer,
    VCardTitle,
    VCardActions,
    VFileInput,
    VLayout,
    VFlex,
    VRow,
    VContainer,
    VCol,
    VTextField,
    VSubheader,
    VForm,
    VTabs,
    VTab,
    VTabsSlider,
    VTabItem,
    VTooltip,
    VTreeview,
    VCheckbox,
    VProgressCircular,
    VBreadcrumbs,
    VBreadcrumbsItem,
    VDivider,
    VStepperHeader,
    VStepperItems,
    VSelect,
    VBadge,
    VMenu,
    VList,
    VListItem,
    VListItemTitle,
    VListGroup,
    VImg,
    VFooter,
    VMain,
    VSimpleTable,
    VDataTable,
    VSwitch,
    VToolbar,
    VRadio,
    VRadioGroup,
    VSimpleCheckbox,
    VStepper,
    VStepperStep,
    VStepperContent,
    VOverlay,
    VCombobox,
    VSheet,
    VNavigationDrawer,
    VListItemAvatar,
    VListItemContent,
    VListItemIcon,
    VColorPicker,
    VAutocomplete,
    VDatePicker,
    VChip
} from 'vuetify/lib'
import { Ripple } from 'vuetify/lib/directives'
import en from 'vuetify/src/locale/en'
import tr from 'vuetify/src/locale/tr'
import {getSettings} from '@/services/application';

Vue.use(Vuetify, {
    components: {
        VAppBar,
        VAppBarNavIcon,
        VToolbarTitle,
        VBtn,
        VIcon,
        VAvatar,
        VSnackbar,
        VDialog,
        VCard,
        VCardText,
        VSpacer,
        VCardTitle,
        VCardActions,
        VFileInput,
        VLayout,
        VFlex,
        VRow,
        VContainer,
        VCol,
        VTextField,
        VSubheader,
        VForm,
        VTabs,
        VTab,
        VTabsSlider,
        VTabItem,
        VTooltip,
        VTreeview,
        VCheckbox,
        VProgressCircular,
        VBreadcrumbs,
        VBreadcrumbsItem,
        VDivider,
        VStepperHeader,
        VStepperItems,
        VSelect,
        VBadge,
        VMenu,
        VList,
        VListItem,
        VListItemTitle,
        VListGroup,
        VImg,
        VFooter,
        VMain,
        VSimpleTable,
        VDataTable,
        VSwitch,
        VToolbar,
        VRadio,
        VRadioGroup,
        VSimpleCheckbox,
        VStepper,
        VStepperStep,
        VStepperContent,
        VOverlay,
        VCombobox,
        VSheet,
        VNavigationDrawer,
        VListItemAvatar,
        VListItemContent,
        VListItemIcon,
        VColorPicker,
        VAutocomplete,
        VDatePicker,
        VChip
    },
    directives: {
        Ripple
    }
});

export default new Vuetify({
    icons: {
        iconfont: 'mdi'
    },
    theme: {
        disable: false,
        dark: true,
        options: {
            customProperties: true
        },

    },
    lang: {
        locales: { en, tr },
        current: 'en',
    },
});
