apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform360ramclientv2.fullname" . }}
  labels:
    {{- include "platform360ramclientv2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: app
      protocol: TCP
      name: http
  selector:
    {{- include "platform360ramclientv2.selectorLabels" . | nindent 4 }}



